[tasks.run]
command = "cargo"
args = ["run"]

[tasks.clean_html]
command = "find"
args = [".", "-name", "*.html", "-delete"]

[tasks.dockerbuild]
command = "docker"
args = ["build", "-t", "algotrap", "-f", "deployment/Dockerfile", "."]

[tasks.deploy]
dependencies = ["dockerbuild"]
command = "bash"
args = ["-c", """
  if [ ! -f .env ]; then
    echo 'Error: .env file not found.';
    exit 1;
  fi;
  docker run --rm --env-file .env algotrap
"""]
