name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    outputs:
      commit_count: ${{ steps.get_commit_count.outputs.commit_count }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits

      - name: Get new commits
        id: get_commit_count
        run: echo "commit_count=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_OUTPUT

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build binary
        run: cargo build --release --all-targets

      - name: Archive binary
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a algotrap-${{ runner.os }}.zip target/release/algotrap.exe
            echo "ASSET=algotrap-${{ runner.os }}.zip" >> $GITHUB_ENV
          else
            tar -czf algotrap-${{ runner.os }}.tar.gz -C target/release algotrap
            echo "ASSET=algotrap-${{ runner.os }}.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: algotrap-${{ runner.os }}
          path: ${{ env.ASSET }}

  create-release:
    name: Create Release
    needs: [build]
    if: ${{ needs.build.outputs.commit_count > 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          name: Nightly Build ${{ github.run_id }}
          tag_name: nightly-${{ github.run_id }}
          token: ${{ secrets.NIGHTLY_RELEASE_TOKEN }}
          draft: false
          prerelease: false
          files: |
            artifacts/algotrap-Linux/algotrap-Linux.tar.gz
            artifacts/algotrap-macOS/algotrap-macOS.tar.gz
            artifacts/algotrap-Windows/algotrap-Windows.zip
