name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pre-check:
    name: Pre-check
    runs-on: ubuntu-latest
    outputs:
      commit_count: ${{ steps.get_commit_count.outputs.commit_count }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits

      - name: Get new commits
        id: get_commit_count
        run: echo "commit_count=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: [pre-check]
    if: ${{ needs.pre-check.outputs.commit_count > 0 }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build binaries
        run: cargo build --workspace --release --all-targets

      - name: Archive binaries
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a algotrap-${{ runner.os }}.zip target/release/libalgotrap.dll target/release/cryptobot.exe
            echo "ASSET=algotrap-${{ runner.os }}.zip" >> $GITHUB_ENV
          else
            tar -czf algotrap-${{ runner.os }}.tar.gz -C target/release libalgotrap.d libalgotrap.rlib cryptobot
            echo "ASSET=algotrap-${{ runner.os }}.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: algotrap-${{ runner.os }}
          path: ${{ env.ASSET }}

  build-musl:
    name: Build MUSL
    needs: [pre-check]
    if: ${{ needs.pre-check.outputs.commit_count > 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-musl

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build binaries
        run: cargo build --workspace --release --target x86_64-unknown-linux-musl

      - name: Archive binarise
        shell: bash
        run: |
          tar -czf algotrap-x86_64-unknown-linux-musl.tar.gz -C target/x86_64-unknown-linux-musl/release libalgotrap.d libalgotrap.rlib cryptobot
          echo "ASSET=algotrap-x86_64-unknown-linux-musl.tar.gz" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: algotrap-x86_64-unknown-linux-musl
          path: ${{ env.ASSET }}

  create-release:
    name: Create Release
    needs: [build, build-musl, pre-check]
    if: ${{ needs.pre-check.outputs.commit_count > 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          name: Nightly Build ${{ github.run_id }}
          tag_name: nightly-${{ github.run_id }}
          token: ${{ secrets.NIGHTLY_RELEASE_TOKEN }}
          draft: false
          prerelease: false
          files: |
            artifacts/algotrap-Linux/algotrap-Linux.tar.gz
            artifacts/algotrap-macOS/algotrap-macOS.tar.gz
            artifacts/algotrap-Windows/algotrap-Windows.zip
            artifacts/algotrap-x86_64-unknown-linux-musl/algotrap-x86_64-unknown-linux-musl.tar.gz

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: [create-release]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repository name to lowercase
        id: repo_lowercase
        run: echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (base)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: |
            ghcr.io/${{ steps.repo_lowercase.outputs.repo }}-bins:latest
            ghcr.io/${{ steps.repo_lowercase.outputs.repo }}-bins:nightly-${{ github.run_id }}

      - name: Build and push Docker image (bins)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bins/cryptobot/deployment/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo_lowercase.outputs.repo }}-cryptobot:latest
            ghcr.io/${{ steps.repo_lowercase.outputs.repo }}-cryptobot:nightly-${{ github.run_id }}